//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuType
    {
        public MenuType()
        {
            this.Menus = new HashSet<Menu>();
        }
    
        public int MenuTypeID { get; set; }
        public string MenuName { get; set; }
    
        public virtual ICollection<Menu> Menus { get; set; }
    }
}
